name: .NET

on:
  push:
    tags:
      - "v*.*.*"   # runs only when you push a tag like v1.2.3

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: |
        dotnet build --no-restore
        VERSION=${GITHUB_REF_NAME}
        cp "bin/Release/netstandard2.1/Silk Access.dll" "bin/Release/netstandard2.1/Silk -access-$version.dll"

      - name: Create Release & Upload dll
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          generate_release_notes: true
          files: "bin/Release/netstandard2.1/Silk-Access-${{ github.ref_name }}.dll"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
